routes/web.php
<?php

use App\Models\House;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $houses = House::with('status')->paginate(8);

    return view('welcome',compact('houses'));
});



// dashboard routes
Route::group(['middleware' => 'auth', 'prefix' => 'dashboard'], function() {

    Route::get('/', function(){
        return view('dashboard');
    })->name('dashboard');

    Route::resource('houses', 'HouseController');


});


require __DIR__.'/auth.php';

app/Models/House.php
<?php

namespace App\Models;

use GuzzleHttp\Psr7\UploadedFile;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class House extends Model
{
    use HasFactory;
//$table->string('name');
//$table->string('type');
//
//$table->integer('square_meters');
//$table->integer('rooms_amount');
//
//$table->string('price');
//$table->foreignId('status_id');
    protected $fillable = [
        'name',
        'type',
        'square_meters',
        'rooms_amount',
        'price',
        'status_id'
    ];

    protected $casts = [
        'square_meters' => 'string',
        'type' => 'string',
        'rooms_amount' => 'integer',
        'price' => 'string',
        'status_id' => 'integer'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function status(){
        return $this->belongsTo(Status::class);
    }

    public function storeImage($file){

        $fileName = $file->getClientOriginalName();

        return $file->storeAs('/', $fileName, 'uploads');

    }

    public function sold(){

        if($this->status_id == 4){
            return true;
        }

        return false;

    }


}

app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    use HasFactory;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function houses(){
        return $this->hasMany(House::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HouseController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreHouseRequest;
use App\Models\House;
use App\Models\Status;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Arr;

use App\Helpers\Flash;
/**
 * Class HouseController
 * @package App\Http\Controllers
 */
class HouseController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index(){

        $houses = House::with('status')->paginate(8);

        return view('house.index', compact('houses'));

    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create(){

        $statuses = Status::all();

        return view('house.create', compact('statuses'));

    }

    /**
     * @param StoreHouseRequest $storeHouseRequest
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreHouseRequest $storeHouseRequest){

        $house = House::create($storeHouseRequest->except(['house_image']));

        if($storeHouseRequest->hasFile('house_image')){
            $house->image_uri = $house->storeImage($storeHouseRequest->file('house_image'));
            $house->save();
        }
        
        Flash::success('Het huis is toegevoegd!');

        return redirect()->route('houses.index');


    }

    /**
     * @param House $house
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(House $house){

        if(!$house->delete()){
            abort('400', 'Er ging iets mis.');
        }

        if($house->image_uri){
            Storage::disk('uploads')->delete($house->image_uri);
        }
        
        Flash::success('Het huis is verwijderd uit de database!');
        
        return redirect()->back();

    }

    /**
     * @param House $house
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function edit(House $house){

        $statuses = Status::all();

        return view('house.edit', compact('house','statuses'));

    }


    /**
     * @param StoreHouseRequest $storeHouseRequest
     * @param House $house
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(StoreHouseRequest $storeHouseRequest, House $house){

        $house->update($storeHouseRequest->validated());

        if( $storeHouseRequest->has('house_image') ){
            $house->image_uri = $house->storeImage($storeHouseRequest->file('house_image'));
            $house->save();
        }

        Flash::success('Huis: ' . $house->name . ' is geupdated!');

        return redirect()->back();


    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    Welkom {{auth()->user()->name}} op je persoonlijke dashboard!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/house/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h1 class="text-5xl mb-10">Een nieuw huis toevoegen</h1>
                    <form action="{{route('houses.store')}}" method="POST">
                        @csrf
                        <div class="field">
                            <input type="text" name="name" placeholder="Naam">
                        </div>
                        <div class="field mt-2">
                            <select name="type" id="type">
                                <option value="">Selecteer Type</option>
                                <option value="rijtjeshuis">Rijtjeshuis</option>
                                <option value="rijtjeshuis">Appartement</option>
                                <option value="rijtjeshuis">Vrijstaand</option>
                            </select>
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="square_meters" placeholder="m2">
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="rooms_amount" placeholder="Aantal kamers">
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="price" placeholder="Prijs">
                        </div>
                        <div class="field mt-2">
                            <select name="status_id" id="status_id">
                                @foreach($statuses as $status)
                                    <option value="{{$status->id}}">{{$status->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="field mt-2">
                            <label for="house_image">Upload een foto</label><br>
                            <input type="file" name="house_image">
                        </div>
                        <div class="mt-10">
                            <input type="submit" class="mt-5 p-2 bg-blue-700 text-white" value="Huis toevoegen" formenctype="multipart/form-data"/>
                        </div>
                    </form>
                    @if ($errors->any())
                        <div class="alert alert-danger bg-red-700 text-white mt-5">
                            <ul class="p-10">
                                @foreach ($errors->all() as $error)
                                    <li class="mt-5">{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/house/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h1 class="text-5xl mb-10">Huis: <strong>{{$house->name}}</strong> bewerken</h1>
                    @if($house->image_uri)
                        <img src="{{asset('/uploads/'.$house->image_uri)}}" alt="jaja" >
                    @endif
                    <form action="{{route('houses.update', $house->id)}}" method="POST">
                        @csrf
                        @method('put')
                        <div class="field">
                            <input type="text" name="name" placeholder="Naam" value="{{$house->name}}">
                        </div>
                        <div class="field mt-2">
                            <select name="type" id="type">
                                <option value="rijtjeshuis"
                                    @if($house->type == 'rijtjeshuis')
                                        selected
                                    @endif
                                >Rijtjeshuis</option>
                                <option value="appartement"
                                    @if($house->type == 'appartement')
                                        selected
                                    @endif
                                >Appartement</option>
                                <option value="vrijstaand"
                                    @if($house->type == 'vrijstaand')
                                        selected
                                    @endif
                                >Vrijstaand</option>
                            </select>
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="square_meters" placeholder="Vierkante meters" value="{{$house->square_meters}}">
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="rooms_amount" placeholder="Aantal kamers" value="{{$house->rooms_amount}}">
                        </div>
                        <div class="field mt-2">
                            <input type="number" name="price" placeholder="Prijs" value="{{$house->price}}">
                        </div>
                        <div class="field mt-2">
                            <select name="status_id" id="status_id">
                                @foreach($statuses as $status)
                                    <option value="{{$status->id}}"
                                        @if($status->id == $house->status_id)
                                            selected
                                        @endif
                                    >{{$status->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="field mt-2">
                            <label for="house_image">Wijzig afbeelding</label><br>
                            <input type="file" name="house_image">
                        </div>
                        <div class="mt-10">
                            <input type="submit" class="mt-5 p-2 bg-blue-700 text-white" value="Huis updaten" formenctype="multipart/form-data"/>
                        </div>
                    </form>
                    @if ($errors->any())
                        <div class="alert alert-danger bg-red-700 text-white mt-5">
                            <ul class="p-10">
                                @foreach ($errors->all() as $error)
                                    <li class="mt-5">{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/house/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <h1 class="text-5xl mb-10">Huizen</h1>
                    <table class="min-w-max w-full table-auto">
                        <thead>
                            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                <th class="py-3 px-6 text-left">Naam</th>
                                <th class="py-3 px-6 text-left">Prijs</th>
                                <th class="py-3 px-6 text-left">Status</th>
                                <th class="py-3 px-6 text-left">Acties</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($houses as $house)
                                <tr class="border-b border-gray-200 hover:bg-gray-100">
                                    <td class="py-3 px-6 text-left">{{$house->name}}</td>
                                    <td class="py-3 px-6 text-center">{{$house->price}}</td>
                                    <td class="py-3 px-6 text-center">{{$house->status->name}}</td>
                                    <td class="py-3 px-6 text-center flex justify-end">
                                        <form action="{{route('houses.destroy', $house->id)}}" method="POST">
                                            @method('delete')
                                            @csrf
                                            <input type="submit" onclick="confirm('Weet je het zeker dat je huis:{{$house->name}} wilt verwijderen?')" class="p-2 bg-red-700 text-white cursor-pointer" value="verwijderen">
                                        </form>
                                        <a href="{{route('houses.edit', $house->id)}}" class="p-2 bg-green-600 text-white ml-1">wijzigen</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="my-10">
                        {{$houses->links()}}

                    </div>
                    <div class="mt-10">
                        <a href="{{route('houses.create')}}" class="mt-5 p-2 bg-blue-700 text-white">Nieuw huis toevoegen</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                @if(session()->has('message'))
                    <div class="message {{session()->pull('message.type')}} text-white">
                        {{session()->pull('message.content')}}
                    </div>
                @endif

                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                    <x-nav-link :href="route('houses.index')">{{__('Huizen')}}</x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                <div class="flex-shrink-0">
                    <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                </div>

                <div class="ml-3">
                    <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>